version: '3.8'

services:
  go-web-service:
    image: webservice
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-web-service
    ports:
      - "8080:8080"
    command: /Application/go-web-service
    restart: always

  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/panel.json:/etc/grafana/provisioning/dashboards/exported_dashboard.json
    environment:
      - GF_INSTALL_PLUGINS=grafana-simple-json-datasource
      - GF_SECURITY_ADMIN_USERNAME=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/exported_dashboard.json
    depends_on:
      - prometheus